# -*- ruby -*-

# /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# install the packages in this brew file:
# `brew bundle install`

# Install applications globally.
cask_args appdir: "/Applications", "no-quarantine": true

# brew taps.
tap "dart-lang/dart"
tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "sass/sass"
tap "timidrobot/tap"

# Applications to install.
cask "atom"
cask "emacs"
cask "firefox"
cask "forticlient-vpn"
cask "github"
cask "go2shell"
cask "google-chrome"
cask "handbrake"
cask "iina"
cask "intellij-idea"
cask "iterm2"
cask "keyboard-maestro"
cask "lastpass"
# cask "logitech-control-center"
cask "microsoft-remote-desktop"
cask "microsoft-teams"
cask "mpv"
cask "mysqlworkbench"
cask "nvalt"
cask "onedrive"
cask "oxygen-xml-editor"
cask "phpstorm"
cask "postman"
cask "pycharm"
cask "rectangle"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "transmission"
cask "transmission-remote-gui"
cask "vagrant"
cask "vienna"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vlc"
cask "webstorm"
cask "whatsapp"
cask "xscreensaver"
cask "zoom"

# ordered packages
brew "php@7.4"
brew "composer", 'ignore-dependencies': true # must be after php.

brew "bash-completion"
brew "bat"
brew "bat-extras"
brew "clamav"
brew "cmc"
brew "coreutils"
brew "curl"
brew "ffmpeg"
brew "flac"
brew "git"
brew "httpd"
brew "hub"
brew "imagemagick"
brew "jing-trang"
brew "jq"
brew "keyboard-maestro"
brew "lame"
brew "lnav"
brew "mailhog"
brew "mariadb"
brew "maven"
brew "moreutils"
brew "node"
brew "openjdk"
brew "pv"
brew "rename"
brew "ruby"
brew "sass"
brew "saxon"
brew "shellcheck"
brew "solr"
brew "sqlite"
brew "ssh-copy-id"
brew "tidy-html5"
brew "tree"
brew "wget"
brew "yarn"

