
# Install applications globally.
cask_args appdir: "/Applications"

# Useful taps.
tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "sass/sass"

# Applications to install.
# cask "smcfancontrol"
# cask "emacs"
# cask "db-browser-for-sqlite"
# cask "firefox"
# cask "gephi"
# cask "go2shell"
# cask "google-chrome"
# cask "handbrake"
# cask "iterm2"
# cask "libreoffice"
# cask "mpv"
# cask "mysqlworkbench"
# cask "netbeans"
# cask "oxygen-xml-editor"
# cask "phpstorm"
# cask "postman"
# cask "shiftit"
# cask "sizzlingkeys"
# cask "sourcetree"
# cask "spotify"
# cask "transmission-remote-gui"
# cask "transmission"
# cask "vienna"
# cask "virtualbox"
# cask "virtualbox-extension-pack"
# cask "vlc"
# cask "vagrant"

# packages.
brew "ant@1.9", link: true
brew "autoconf"
brew "bash-completion"
brew "bagit"
brew "bower"
brew "composer"
brew "ffmpeg"
brew "gawk"
brew "gettext", link: true
brew "git"
brew "icu4c"
brew "imagemagick"
brew "lame"
brew "maven"
brew "mysql", restart_service: true, link: true
brew "ncftp"
brew "node"
brew "npm"
brew "openssl"
brew "pcre"
brew "php@5.6", restart_service: true, link: true
brew "pkg-config"
brew "python"
brew "readline"
brew "saxon"
brew "sqlite"
brew "ssh-copy-id"
brew "tidy-html5"
brew "wget"
brew "x264"
brew "yarn"
